### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [CPAD2021SecA/SecAGroup01#1]
Please provide list of screens that your app will have

**Comment by deliadsouza** [comment]
List of screens - 
1. Login / Sign up
2. Home Page
3. Description Page (Consisting of description for a particular place)
4. Payment Screen
5. Review Screen
6. User Profile page

**Comment by Sayantan-Pal-2020SP93050** [comment]
> Please provide list of screens that your app will have

Updated Sir. Thank You

**Comment by VinayaSathyanarayana** [comment]
Closed
